name = "proofaid"
compatibility_date = "2025-09-27"

[build]
command = "npm --prefix dashboard ci && npm --prefix dashboard run build"
watch_dir = "dashboard/src"

[assets]
directory = "dashboard/dist"

[vars]
CELO_NETWORK_KEY = "celoSepolia"
CELO_CHAIN_ID = "11142220"
CELO_RPC_URL = "https://forno.celo-sepolia.celo-testnet.org"
AID_PROGRAM_ADDRESS = "0x79A8F888607A5aeb77B7DC80a78E2202274AcAce"
BENEFICIARY_REGISTRY_ADDRESS = "0xF248728fD82E441b298c15C114C86d7ab458c35f"
AID_VOUCHER_ADDRESS = "0x52b08173aA985C2d46C4162b443656Fb7D8a8dB0"
DISTRIBUTION_EVENT_ADDRESS = "0x8a41D038F929B25595e6B3Bc9ABf83E3CA682bD6"
